name: Metrics Embed
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github_metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{secrets.METRICS_TOKEN}}
          plugin_isocalendar: yes
          plugin_isocalendar_duration: year
          
          plugin_languages: yes
          
          plugin_habits: yes
          plugin_habits_days: 69
          
          plugin_lines: yes
          
          plugin_achievements: yes
          
          plugin_notable: yes
          
          plugin_wakatime: yes
          plugin_wakatime_token: ${{secrets.WAKATIME_API_TOKEN}}
          plugin_wakatime_days: 7
          plugin_wakatime_user: .user.login
          
